# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jnh3el5EN5aVkkAJs5eR5sgj-tKlQWLh
"""
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
import numpy as np
import re
import nltk
nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords
import pandas as pd
import nltk
nltk.download('wordnet')
from sklearn.metrics import classification_report
import joblib
from sklearn.metrics import confusion_matrix
import pickle





# Importing data
movie_data = pd.read_csv("final_movie_reviews.csv")


# in X text and in y the related score
X, y = movie_data.stop_tokens, movie_data.score_indexed

cv = CountVectorizer()

X = cv.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=33)

# Naive Bayes Classifier

clf = MultinomialNB()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
import joblib
joblib.dump(clf, 'NB_movie_reviews_model.pkl')

# load and use saved model later

NB_model = open('NB_movie_reviews_model.pkl','rb')
clf = joblib.load(NB_model)


